name: pkgcruft
description: Run pkgcruft over an ebuild repository
inputs:
  args:
    description: Arguments to pass to pkgcruft
    required: false
    default: ''
runs:
  using: composite
  steps:
    - uses: cargo-bins/cargo-binstall@main

    - name: Install pkgcraft-tools
      shell: bash
      run: cargo binstall pkgcraft-tools

    - name: Install pkgcruft
      shell: bash
      run: cargo binstall pkgcruft

    - name: Cache pkgcruft
      uses: actions/cache@v4
      with:
        path: ~/.cache/pkgcraft
        key: pkgcraft

    - name: Run pkgcruft action
      shell: bash
      run: ./pkgcruft-action
