name: pkgcruft
description: Scan a Gentoo ebuild repository using pkgcruft.
branding:
  color: "purple"
  icon: "package"

inputs:
  exit:
    description: report sets that trigger failures
    required: false
    type: string
    default: '@critical,@error'
  repo:
    description: Path to ebuild repo
    required: false
    type: string
    default: './'
  pr-comments:
    description: Enable pull request comment support
    required: false
    type: boolean
    default: 'true'
  git:
    description: Use pkgcraft from git
    required: false
    type: boolean
    default: 'false'

runs:
  using: composite
  steps:
    - uses: cargo-bins/cargo-binstall@main

    - name: Install pkgcraft tools
      id: install
      shell: bash
      run: |
        if ${{ inputs.git }}; then
          cargo install pkgcraft-tools --git https://github.com/pkgcraft/pkgcraft.git
          cargo install pkgcruft --git https://github.com/pkgcraft/pkgcraft.git
        else
          cargo binstall --target x86_64-unknown-linux-gnu pkgcraft-tools pkgcruft
        fi

        pk --version
        pkgcruft --version
        echo "pk=$(pk --version)" >> $GITHUB_OUTPUT
        echo "pkgcruft=$(pkgcruft --version)" >> $GITHUB_OUTPUT

    - name: Restore cache
      id: restore-cache
      uses: actions/cache/restore@v4
      with:
        path: ~/.cache/pkgcruft
        key: ${{ github.ref_name }}-${{ steps.install.outputs.pk }}-${{ steps.install.outputs.pkgcruft }}-repo-${{ hashFiles(format('{0}/**/*', inputs.repo)) }}
        restore-keys: |
          ${{ github.ref_name }}-
          ${{ github.event.repository.default_branch }}-

    - name: Set environment
      shell: bash
      run: |
        echo "PKGCRUFT_EXIT=${{ inputs.exit }}" >> $GITHUB_ENV
        echo "PR_COMMENTS=${{ inputs.pr-comments }}" >> $GITHUB_ENV
        echo "GIT_DEFAULT_BRANCH=${{ github.event.repository.default_branch }}" >> $GITHUB_ENV
        echo "GH_PR=${{ github.event.number }}" >> $GITHUB_ENV
        echo "GIT_BASE_BRANCH=${{ github.base_ref }}" >> $GITHUB_ENV
        echo "GIT_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV

        # add action path to $PATH
        echo "${{ github.action_path }}" >> $GITHUB_PATH

    - name: Run pkgcruft action
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        cd "${{ inputs.repo }}"
        pkgcruft-action

    - name: Save cache
      if: ${{ github.base_ref == '' && steps.restore-cache.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v4
      with:
        path: ~/.cache/pkgcruft
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}
