name: pkgcruft
description: Run pkgcruft over an ebuild repository
inputs:
  options:
    description: Options to pass to `pkgcruft scan`
    required: false
    default: ''
  repo:
    description: Path to ebuild repo
    required: false
    default: './'

runs:
  using: composite
  steps:
    # TODO: re-enable cargo-binstall on next releases with embedded Cargo.toml binstall metadata
    #- uses: cargo-bins/cargo-binstall@main
    #
    #- name: Install pkgcraft-tools
    #  shell: bash
    #  run: cargo binstall --target x86_64-unknown-linux-gnu pkgcraft-tools

    #- name: Install pkgcruft
    #  shell: bash
    #  run: cargo binstall --target x86_64-unknown-linux-gnu pkgcruft

    # TODO: remove this once the above binstall method works
    - name: Install pkgcraft tools
      shell: bash
      run: |
        curl -sL https://github.com/pkgcraft/pkgcraft/releases/download/pkgcraft-tools-0.0.16/pkgcraft-tools-0.0.16-x86_64-unknown-linux-gnu.tar.xz | tar -Jxvf - -C ~/.cargo/bin
        curl -sL https://github.com/pkgcraft/pkgcraft/releases/download/pkgcruft-0.0.3/pkgcruft-0.0.3-x86_64-unknown-linux-gnu.tar.xz | tar -Jxvf - -C ~/.cargo/bin

    - name: Cache pkgcruft
      uses: actions/cache@v4
      with:
        path: ~/.cache/pkgcraft
        key: pkgcraft

    - name: Set environment
      shell: bash
      run: |
        echo "PKGCRUFT_SCAN_OPTIONS=${{ inputs.options }}" >> $GITHUB_ENV
        echo "REPO=${{ inputs.repo }}" >> $GITHUB_ENV

        # add action path to $PATH
        echo "${{ github.action_path }}" >> $GITHUB_PATH

    - name: Run pkgcruft action
      id: action
      shell: bash
      run: pkgcruft-action
