name: pkgcruft
description: Scan a Gentoo ebuild repository using pkgcruft.
branding:
  color: "purple"
  icon: "package"

inputs:
  repo:
    description: Path to ebuild repo
    required: false
    default: './'

runs:
  using: composite
  steps:
    # TODO: re-enable cargo-binstall on next releases with embedded Cargo.toml binstall metadata
    #- uses: cargo-bins/cargo-binstall@main
    #
    #- name: Install pkgcraft-tools
    #  shell: bash
    #  run: cargo binstall --target x86_64-unknown-linux-gnu pkgcraft-tools

    #- name: Install pkgcruft
    #  shell: bash
    #  run: cargo binstall --target x86_64-unknown-linux-gnu pkgcruft

    # TODO: remove this once the above binstall method works
    - name: Install pkgcraft tools
      id: install
      shell: bash
      run: |
        curl -sL https://github.com/pkgcraft/pkgcraft/releases/download/pkgcraft-tools-0.0.16/pkgcraft-tools-0.0.16-x86_64-unknown-linux-gnu.tar.xz | tar -Jxvf - -C ~/.cargo/bin
        curl -sL https://github.com/pkgcraft/pkgcraft/releases/download/pkgcruft-0.0.3/pkgcruft-0.0.3-x86_64-unknown-linux-gnu.tar.xz | tar -Jxvf - -C ~/.cargo/bin
        echo "pkgcraft-tools=$(pk --version)" >> $GITHUB_OUTPUT
        echo "pkgcruft=$(pkgcruft --version)" >> $GITHUB_OUTPUT

    - name: Cache repo metadata and pkgcruft output
      uses: actions/cache@v4
      with:
        path: ~/.cache/pkgcruft
        key: ${{ runner.os }}-${{ steps.install.outputs.pkgcraft-tools }}-${{ steps.install.outputs.pkgcruft }}
        restore-keys: ${{ runner.os }}-

    - name: Set environment
      shell: bash
      run: |
        echo "REPO=${{ inputs.repo }}" >> $GITHUB_ENV
        echo "GIT_BASE_BRANCH=${{ github.base_ref }}" >> $GITHUB_ENV
        echo "GIT_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV

        # add action path to $PATH
        echo "${{ github.action_path }}" >> $GITHUB_PATH

    - name: Run pkgcruft action
      shell: bash
      run: pkgcruft-action
