name: pkgcruft
description: Scan a Gentoo ebuild repository using pkgcruft.
branding:
  color: "purple"
  icon: "package"

inputs:
  repo:
    description: Path to ebuild repo
    required: false
    default: './'
  git:
    description: Use pkgcraft from git
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - uses: cargo-bins/cargo-binstall@main

    - name: Install pkgcraft tools
      id: install
      shell: bash
      run: |
        if [[ ${{ inputs.git }} == "true" ]]; then
          cargo install pkgcraft-tools --git https://github.com/pkgcraft/pkgcraft.git
          cargo install pkgcruft --git https://github.com/pkgcraft/pkgcraft.git
        else
          cargo binstall --target x86_64-unknown-linux-gnu pkgcraft-tools
          cargo binstall --target x86_64-unknown-linux-gnu pkgcruft
        fi

        pk --version
        pkgcruft --version
        echo "pkgcraft-tools=$(pk --version)" >> $GITHUB_OUTPUT
        echo "pkgcruft=$(pkgcruft --version)" >> $GITHUB_OUTPUT

    - name: Restore cache
      id: restore-cache
      uses: actions/cache/restore@v4
      with:
        path: ~/.cache/pkgcruft
        key: ${{ github.ref_name }}-${{ steps.install.outputs.pkgcraft-tools }}-${{ steps.install.outputs.pkgcruft }}-repo-${{ hashFiles(format('{0}/**/*', inputs.repo)) }}
        restore-keys: |
          ${{ github.ref_name }}-
          ${{ github.event.repository.default_branch }}-

    - name: Set environment
      shell: bash
      run: |
        echo "REPO=${{ inputs.repo }}" >> $GITHUB_ENV
        echo "GIT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "GIT_DEFAULT_BRANCH=${{ github.event.repository.default_branch }}" >> $GITHUB_ENV
        echo "GH_PR=${{ github.event.number }}" >> $GITHUB_ENV
        echo "GIT_BASE_BRANCH=${{ github.base_ref }}" >> $GITHUB_ENV
        echo "GIT_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV

        # add action path to $PATH
        echo "${{ github.action_path }}" >> $GITHUB_PATH

    - name: Run pkgcruft action
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: pkgcruft-action

    - name: Save cache
      if: ${{ github.base_ref == '' && steps.restore-cache.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v4
      with:
        path: ~/.cache/pkgcruft
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}
