name: pkgcruft
description: Run pkgcruft over an ebuild repository
inputs:
  options:
    description: Options to pass to `pkgcruft scan`
    required: false
    default: ''
  repo:
    description: Path to ebuild repo
    required: false
    default: './'
outputs:
  exit-status:
    description: "Action exit status"
    value: ${{ steps.action.outputs.exit-status }}

runs:
  using: composite
  steps:
    # TODO: re-enable cargo-binstall on next releases with embedded Cargo.toml binstall metadata
    #- uses: cargo-bins/cargo-binstall@main
    #
    #- name: Install pkgcraft-tools
    #  shell: bash
    #  run: cargo binstall --target x86_64-unknown-linux-gnu pkgcraft-tools

    #- name: Install pkgcruft
    #  shell: bash
    #  run: cargo binstall --target x86_64-unknown-linux-gnu pkgcruft

    # TODO: remove this once the above binstall method works
    - name: Install pkgcraft tools
      shell: bash
      run: |
        curl -sL https://github.com/pkgcraft/pkgcraft/releases/download/pkgcraft-tools-0.0.16/pkgcraft-tools-0.0.16-x86_64-unknown-linux-gnu.tar.xz | tar -Jxvf - -C ~/.cargo/bin
        curl -sL https://github.com/pkgcraft/pkgcraft/releases/download/pkgcruft-0.0.3/pkgcruft-0.0.3-x86_64-unknown-linux-gnu.tar.xz | tar -Jxvf - -C ~/.cargo/bin

    # currently pkgcraft can't handle repo syncing
    # see https://github.com/pkgcraft/pkgcruft-action/issues/2
    - name: Checkout Gentoo repo and mangle /etc/portage/repos.conf
      shell: bash
      run: |
        mkdir -p "${HOME}/.cache/pkgcruft/repos/gentoo"
        curl -sL https://github.com/gentoo-mirror/gentoo/archive/stable.tar.gz | tar -zxf - --strip-components=1 -C "${HOME}/.cache/pkgcruft/repos/gentoo"

        dir=$(mktemp -d)
        cat <<- EOF > "${dir}/repos.conf"
        [DEFAULT]
        main-repo = gentoo

        [gentoo]
        location = "${HOME}/.cache/pkgcruft/repos/gentoo"
        EOF

        sudo mv "${dir}" /etc/portage

    - name: Cache pkgcruft
      uses: actions/cache@v4
      with:
        path: ~/.cache/pkgcraft
        key: pkgcraft

    - name: Set environment
      shell: bash
      run: |
        echo "PKGCRUFT_SCAN_OPTIONS=${{ inputs.options }}" >> $GITHUB_ENV
        echo "REPO=${{ inputs.repo }}" >> $GITHUB_ENV

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run pkgcruft action
      id: action
      shell: bash
      run: pkgcruft-action
