name: pkgcruft
description: Scan a Gentoo ebuild repository using pkgcruft.
branding:
  color: "purple"
  icon: "package"

inputs:
  exit:
    description: report sets that trigger failures
    required: false
    type: string
    default: '@critical,@error'
  repo:
    description: Path to ebuild repo
    required: false
    type: string
    default: './'
  pr-comments:
    description: Enable pull request comment support
    required: false
    type: boolean
    default: 'true'
  pkgcraft-tools:
    description: pkgcraft-tools version
    required: false
    type: string
    default: '0.0.31'
  pkgcruft:
    description: pkgcruft version
    required: false
    type: string
    default: '0.0.18'

runs:
  using: composite
  steps:
    - name: Restore cache
      id: restore-cache
      uses: actions/cache/restore@v5
      with:
        path: ~/.cache/pkgcruft
        key: ${{ github.ref_name }}:pk-${{ inputs.pkgcraft-tools }}:pkgcruft-${{ inputs.pkgcruft }}:repo-${{ hashFiles(format('{0}/**/*', inputs.repo)) }}
        restore-keys: |
          ${{ github.ref_name }}:pk-${{ inputs.pkgcraft-tools }}:pkgcruft-${{ inputs.pkgcruft }}:
          ${{ github.ref_name }}:
          ${{ github.event.repository.default_branch }}:

    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@main

    - name: Install tools
      shell: bash
      run: |
        if [[ ${{ inputs.pkgcraft-tools }} == "git" ]]; then
          cargo install pkgcraft-tools --git https://github.com/pkgcraft/pkgcraft.git
        else
          cargo binstall --target x86_64-unknown-linux-gnu pkgcraft-tools@${{ inputs.pkgcraft-tools }}
        fi

        if [[ ${{ inputs.pkgcruft }} == "git" ]]; then
          cargo install pkgcruft --git https://github.com/pkgcraft/pkgcraft.git
        else
          cargo binstall --target x86_64-unknown-linux-gnu pkgcruft@${{ inputs.pkgcruft }}
        fi

    - name: Show tool versions
      shell: bash
      run: |
        pk --version
        pkgcruft --version

    - name: Initialize action environment
      shell: bash
      run: |
        echo "PKGCRUFT_EXIT=${{ inputs.exit }}" >> $GITHUB_ENV
        echo "PR_COMMENTS=${{ inputs.pr-comments }}" >> $GITHUB_ENV
        echo "GIT_DEFAULT_BRANCH=${{ github.event.repository.default_branch }}" >> $GITHUB_ENV
        echo "GH_PR=${{ github.event.number }}" >> $GITHUB_ENV
        echo "GIT_BASE_BRANCH=${{ github.base_ref }}" >> $GITHUB_ENV
        echo "GIT_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV

        # add action path to $PATH
        echo "${{ github.action_path }}" >> $GITHUB_PATH

    - name: Run pkgcruft action
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        cd "${{ inputs.repo }}"
        pkgcruft-action

    - name: Save cache
      if: ${{ github.base_ref == '' && steps.restore-cache.outputs.cache-hit != 'true' && inputs.pkgcraft-tools != 'git' && inputs.pkgcruft != 'git' }}
      uses: actions/cache/save@v5
      with:
        path: ~/.cache/pkgcruft
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}
