name: ci

on:
  push:
    branches: ['**']
    paths-ignore:
      - "*.md"
  pull_request:
    branches: [main]
    paths:
      - "action.yml"
      - "pkgruft-action"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Checkout shared testdata
      uses: actions/checkout@v4
      with:
        repository: pkgcraft/pkgcraft-testdata
        path: testdata

    - name: Test pkgcruft-action
      uses: ./
      with:
        repo: ./testdata/repos/valid/qa-primary
