name: ci

on:
  push:
    branches: ['**']
    paths-ignore:
      - "*.md"
  pull_request:
    branches: [main]
    paths:
      - "action.yml"
      - "pkgruft-action"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Checkout shared testdata
      uses: actions/checkout@v4
      with:
        repository: pkgcraft/pkgcraft-testdata
        path: testdata

    - name: Set environment
      shell: bash
      run: echo "PKGCRUFT_ACTION_TEST=1" >> $GITHUB_ENV

    - name: Run against qa-primary repo
      id: scan-qa-primary
      uses: ./
      with:
        repo: ./testdata/repos/valid/qa-primary

    - name: Fail on previous run failure
      if: ${{ steps.scan-qa-primary.outputs.exit-status != '0' }}
      run: exit 1

    - name: Run against repo with invalid ebuilds
      id: scan-bad
      uses: ./
      with:
        repo: ./testdata/repos/valid/bad

    - name: Fail on previous run success
      if: ${{ steps.scan-bad.outputs.exit-status == '0' }}
      run: exit 1
