name: ci

on:
  push:
    branches: ['**']
    paths-ignore:
      - "*.md"
  pull_request:
    branches: [main]
    paths:
      - "action.yml"
      - "pkgruft-action"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Test pkgcruft-action
      uses: ./
      with:
        repo: ./testdata/repos/valid/qa-primary
