name: ci

on:
  push:
    branches: ['**']
    paths-ignore:
      - "*.md"
  pull_request:
    branches: [main]
    paths:
      - "action.yml"
      - "pkgruft-action"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Checkout shared testdata
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        repository: pkgcraft/pkgcraft-testdata
        path: testdata

    - name: Run against repo with invalid ebuilds
      env:
        _PKGCRUFT_ACTION_EXIT_STATUS: 2
      uses: ./
      with:
        repo: testdata/repos/valid/bad

    - name: Run against qa-primary repo
      env:
        _PKGCRUFT_ACTION_EXIT_STATUS: 0
      uses: ./
      with:
        repo: testdata/repos/valid/qa-primary

    - name: Patch qa-primary repo
      working-directory: testdata/repos/valid/qa-primary
      run: |
        for path in $(find -name 'fix.*'); do
          dir=${path%/*}
          file=${path##*/}
          pushd "${dir}" > /dev/null
          if [[ ${file} == fix.patch ]] ; then
            patch -p1 -F0 -N < fix.patch > /dev/null
          else
            ./fix.sh > /dev/null
          fi
          popd > /dev/null
        done

    - name: Run against patched qa-primary repo
      env:
        _PKGCRUFT_ACTION_EXIT_STATUS: 0
      uses: ./
      with:
        repo: testdata/repos/valid/qa-primary
